# Generated by Django 5.1.4 on 2024-12-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtext',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
        migrations.DeleteModel(
            name='GeneratedSummary',
        ),
    ]
